CREATE TABLE IF NOT EXISTS bank_email_notifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenant_id INT NOT NULL,
  gmail_message_id VARCHAR(255) NOT NULL,
  gmail_thread_id VARCHAR(255),
  label_name VARCHAR(120),
  email_from VARCHAR(255),
  email_subject VARCHAR(500),
  email_received_at DATETIME,
  transaction_at DATETIME,
  amount DECIMAL(10,2),
  currency VARCHAR(8) DEFAULT 'BOB',
  destination_account VARCHAR(50),
  origin_account VARCHAR(50),
  payer_name VARCHAR(255),
  origin_bank VARCHAR(255),
  concept VARCHAR(255),
  notification_number VARCHAR(120),
  matched_payment_id INT,
  processed_status ENUM('processed','ignored','unmatched','ambiguous','error') DEFAULT 'unmatched',
  notes VARCHAR(500),
  raw_text TEXT,
  payload JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_tenant_gmail_message (tenant_id, gmail_message_id),
  KEY idx_tenant_status_created (tenant_id, processed_status, created_at),
  KEY idx_transaction_at (tenant_id, transaction_at),
  KEY idx_notification_number (tenant_id, notification_number),
  KEY idx_matched_payment (matched_payment_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (matched_payment_id) REFERENCES payments(id) ON DELETE SET NULL
);
